# Generated by Django 5.0.6 on 2024-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikypics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
